### ISSUE TITLE
No working links in inline order sections

### ISSUE THREAD

**Issue by kappapiana** [alpianon/pandoc-inline-headers#10]
# How to reproduce the issue

Create an ordered list within `--filter=crossref-ordered-list`

Run pandoc, say 

    pandoc  test.md -o test.html --filter=crossref-ordered-list 

## sample code

```markdown
---
numberSections: true
---
# ciao

## ciao ciao

Ciao ciao Ciao

1. riciao [bello]

[bello]: #sec:
```

Remove `numberSections: true, works back

# screenshots: 

doesn't work

![Screenshot from 2019-07-02 22-56-29](https://user-images.githubusercontent.com/25220015/60546069-de8df080-9d1c-11e9-8258-4e12cc9b8cf4.png)

Works

![Screenshot from 2019-07-02 22-59-49](https://user-images.githubusercontent.com/25220015/60546234-30cf1180-9d1d-11e9-9517-cf0fc8221e8c.png)

**Comment by alpianon** [comment]
This depends on how the crossref-ordered-list filter works: to identify section identifiers and other metadata added by user (like in `a. {#sec:test class='my-class'} test text`) it converts pandoc objects to raw text in order to "extract" the identifier and possible other metadata, and reconverts the remainder text to pandoc objects; as a side effect, as you noted, links defined elsewhere in the document get "lost" in the double conversion. 

I have to rewrite the filter in order to spot identifiers by parsing pandoc objects -- even if it may prove a little bit difficult because for instance the previous sample text would be represented by something like:
```
[OrderedList (1,LowerAlpha,Period)
 [[Plain [
  Str "{#sec:test",Space,Str "class=",Quoted SingleQuote [Str "my-class"],Str "}",Space,
  Str "test",Space,Str "text"]
 ]]
]
```
I will try ;)
